image: Visual Studio 2017

platform:
- x64

environment:
  matrix:
    - BUILD_TYPE: x86
    - BUILD_TYPE: x64

before_build:
    - mkdir dic\ipadic

build_script:
    - cd mecab\src
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %BUILD_TYPE%
    - nmake -f Makefile.%BUILD_TYPE%.msvc
    - cd ..\..\
    - mecab\src\mecab-dict-index.exe -d mecab-ipadic -o dic\ipadic -f EUC-JP -t UTF-8

after_build:
    - cd %APPVEYOR_BUILD_FOLDER%\
    - copy mecab-ipadic\dicrc dic\ipadic\dicrc
    - copy mecab-ipadic\*.def dic\ipadic\
    - copy mecab-ipadic\*.csv dic\ipadic\
    - 7z a mecab-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\mecab\src\*.dll
    - 7z a mecab-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\mecab\src\*.exe
    - 7z a mecab-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\mecab\src\*.lib
    - 7z a mecab-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\mecab\src\mecab.h
    - 7z a mecab-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\win\mecabrc
    - 7z a mecab-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\dic

artifacts:
  - path: '*.zip'
    name: MeCab-MSVC
deploy:
  description: 'MeCab-MSVC'
  provider: GitHub
  auth_token:
    secure: wk6H/7XYGdxa7T4A/k+PcHxWngTfJJYAMe2pFVFb7PnMV8vHRSXon9II4EyDomQy
  artifact: MeCab-MSVC
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
