image: Visual Studio 2015
configuration: Release

platform:
- x64

environment:
  matrix:
    - BUILD_TYPE: x86
    - BUILD_TYPE: x64

build_script:
    - call ci\win\build.bat

artifacts:
  - path: '*.zip'
    name: MeCab-MSVC
  - path: 'mecab\python\dist\*.whl'
    name: MeCab-MSVC-wheel

deploy:
  description: 'MeCab-MSVC'
  provider: GitHub
  auth_token:
    secure: wk6H/7XYGdxa7T4A/k+PcHxWngTfJJYAMe2pFVFb7PnMV8vHRSXon9II4EyDomQy
  artifact: MeCab-MSVC,MeCab-MSVC-wheel
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
