export default {
   kanji: {
     'ateji': 'ateji (phonetic) reading',
     'iK': 'word containing irregular kanji usage',
     'ik': 'word containing irregular kana usage',
     'io': 'irregular okurigana usage',
     'oK': 'word containing out-dated kanji',
   },
   reading: {
     'gikun': "gikun (meaning) reading",
     'go': "on-yomi, go",
     'ik': "word containing irregular kana usage",
     'jouyou': "approved reading for jouyou kanji",
     'kan': "on-yomi, kan",
     'kanyou': "on-yomi, kan'you",
     'kun': "kun-yomi",
     'name': "reading used only in names (nanori",
     'oik': "old or irregular kana form",
     'ok': "out-dated or obsolete kana usage",
     'on': "on-yomi",
     'rad': "reading used as name of radical",
     'tou': "on-yomi, tou",
     'uK': "word usually written using kanji alone",
   },
   sense: {
     'abbr': 'abbreviation',
     'aphorism': 'aphorism (pithy saying)',
     'arch': 'archaism',
     'chn': "children's language",
     'col': 'colloquialism',
     'company': 'company name',
     'derog': 'derogatory',
     'eK': 'exclusively kanji',
     'fam': 'familiar language',
     'fem': 'female term, language, or name',
     'given': 'given name or forename, gender not specified',
     'hon': 'honorific or respectful (sonkeigo) language',
     'hum': 'humble (kenjougo) language',
     'id': 'idiomatic expression',
     'joc': 'jocular, humorous term',
     'm-sl': 'manga slang',
     'male': 'male term, language, or name',
     'obs': 'obsolete term',
     'obsc': 'obscure term',
     'on-mim': 'onomatopoeic or mimetic word',
     'organization': 'organization name',
     'person': 'full name of a particular person',
     'place': 'place name',
     'poet': 'poetical term',
     'pol': 'polite (teineigo) language',
     'product': 'product name',
     'proverb': 'proverb',
     'quote': 'quotation',
     'rare': 'rare',
     'sens': 'sensitive',
     'sl': 'slang',
     'station': 'railway station',
     'surname': 'family or surname',
     'uk': 'word usually written using kana alone',
     'unclass': 'unclassified name',
     'vulg': 'vulgar expression or word',
     'work': 'work of art, literature, music, etc. name',
     'X': 'rude or X-rated term (not displayed in educational software)',
     'yoji': 'yojijukugo',
   },
   partOfSpeech: {
     'adj-f': "noun or verb acting prenominally",
     'adj-i': "adjective (keiyoushi)",
     'adj-ix': "yoi/ii i-adjective",
     'adj-kari': "kari adjective (archaic)",
     'adj-ku': "ku adjective (archaic)",
     'adj-na': "adjectival nouns or quasi-adjectives (keiyodoshi)",
     'adj-nari': "archaic/formal form of na-adjective",
     'adj-no': "nouns which may take the genitive case particle `no'",
     'adj-pn': "pre-noun adjectival (rentaishi)",
     'adj-shiku': "shiku adjective (archaic)",
     'adj-t': "`taru' adjective",
     'adv': "adverb (fukushi)",
     'adv-to': "adverb taking the `to' particle",
     'aux': "auxiliary",
     'aux-adj': "auxiliary adjective",
     'aux-v': "auxiliary verb",
     'conj': "conjunction",
     'cop-da': "copula",
     'ctr': "counter",
     'exp': "Expressions (phrases, clauses, etc.)",
     'int': "interjection (kandoushi)",
     'n': "noun (common) (futsuumeishi)",
     'n-adv': "adverbial noun (fukushitekimeishi)",
     'n-pr': "proper noun",
     'n-pref': "noun, used as a prefix",
     'n-suf': "noun, used as a suffix",
     'n-t': "noun (temporal) (jisoumeishi)",
     'num': "numeric",
     'pn': "pronoun",
     'pref': "prefix",
     'prt': "particle",
     'suf': "suffix",
     'unc': "unclassified",
     'v-unspec': "verb unspecified",
     'v1': "Ichidan verb",
     'v1-s': "Ichidan verb - kureru special class",
     'v2a-s': "Nidan verb with 'u' ending (archaic)",
     'v2b-k': "Nidan verb (upper class) with bu ending (archaic)",
     'v2b-s': "Nidan verb (lower class) with bu ending (archaic)",
     'v2d-k': "Nidan verb (upper class) with dzu ending (archaic)",
     'v2d-s': "Nidan verb (lower class) with dzu ending (archaic)",
     'v2g-k': "Nidan verb (upper class) with gu ending (archaic)",
     'v2g-s': "Nidan verb (lower class) with gu ending (archaic)",
     'v2h-k': "Nidan verb (upper class) with hu/fu ending (archaic)",
     'v2h-s': "Nidan verb (lower class) with hu/fu ending (archaic)",
     'v2k-k': "Nidan verb (upper class) with ku ending (archaic)",
     'v2k-s': "Nidan verb (lower class) with ku ending (archaic)",
     'v2m-k': "Nidan verb (upper class) with mu ending (archaic)",
     'v2m-s': "Nidan verb (lower class) with mu ending (archaic)",
     'v2n-s': "Nidan verb (lower class) with nu ending (archaic)",
     'v2r-k': "Nidan verb (upper class) with ru ending (archaic)",
     'v2r-s': "Nidan verb (lower class) with ru ending (archaic)",
     'v2s-s': "Nidan verb (lower class) with su ending (archaic)",
     'v2t-k': "Nidan verb (upper class) with tsu ending (archaic)",
     'v2t-s': "Nidan verb (lower class) with tsu ending (archaic)",
     'v2w-s': "Nidan verb (lower class) with u ending and we conjugation (archaic)",
     'v2y-k': "Nidan verb (upper class) with yu ending (archaic)",
     'v2y-s': "Nidan verb (lower class) with yu ending (archaic)",
     'v2z-s': "Nidan verb (lower class) with zu ending (archaic)",
     'v4b': "Yodan verb with bu ending (archaic)",
     'v4g': "Yodan verb with gu ending (archaic)",
     'v4h': "Yodan verb with `hu/fu' ending (archaic)",
     'v4k': "Yodan verb with ku ending (archaic)",
     'v4m': "Yodan verb with mu ending (archaic)",
     'v4n': "Yodan verb with nu ending (archaic)",
     'v4r': "Yodan verb with `ru' ending (archaic)",
     'v4s': "Yodan verb with su ending (archaic)",
     'v4t': "Yodan verb with tsu ending (archaic)",
     'v5aru': "Godan verb - -aru special class",
     'v5b': "Godan verb with `bu' ending",
     'v5g': "Godan verb with `gu' ending",
     'v5k': "Godan verb with `ku' ending",
     'v5k-s': "Godan verb - Iku/Yuku special class",
     'v5m': "Godan verb with `mu' ending",
     'v5n': "Godan verb with `nu' ending",
     'v5r': "Godan verb with `ru' ending",
     'v5r-i': "Godan verb with `ru' ending (irregular verb)",
     'v5s': "Godan verb with `su' ending",
     'v5t': "Godan verb with `tsu' ending",
     'v5u': "Godan verb with `u' ending",
     'v5u-s': "Godan verb with `u' ending (special class)",
     'v5uru': "Godan verb - Uru old class verb (old form of Eru)",
     'vi': "intransitive verb",
     'vk': "Kuru verb - special class",
     'vn': "irregular nu verb",
     'vr': "irregular ru verb, plain form ends with -ri",
     'vs': "noun or participle which takes the aux. verb suru",
     'vs-c': "su verb - precursor to the modern suru",
     'vs-i': "suru verb - irregular",
     'vs-s': "suru verb - special class",
     'vt': "transitive verb",
     'vz': "Ichidan verb - zuru verb (alternative form of -jiru verbs) ",
   },
   usageDomain: {
     'anat': 'anatomical term',
     'archit': 'architecture term',
     'astron': 'astronomy, etc. term',
     'baseb': 'baseball term',
     'biol': 'biology term',
     'bot': 'botany term',
     'Buddh': 'Buddhist term',
     'bus': 'business term',
     'chem': 'chemistry term',
     'comp': 'computing term',
     'econ': 'economics term',
     'engr': 'engineering term',
     'finc': 'finance term',
     'food': 'food term',
     'geol': 'geology, etc. term',
     'geom': 'geometry term',
     'law': 'law, etc. term',
     'ling': 'linguistics term',
     'MA': 'martial arts term',
     'mahj': 'mahjong term',
     'math': 'mathematics term',
     'med': 'medicine, etc. term',
     'mil': 'military term',
     'music': 'music term',
     'physics': 'physics term',
     'Shinto': 'Shinto term',
     'shogi': 'shogi term',
     'sports': 'sports term',
     'sumo': 'sumo term',
     'zool': 'zoology term',
   },
   dialect: {
     'hob': 'Hokkaidou-ben',
     'ksb': 'Kansai-ben',
     'ktb': 'Kantou-ben',
     'kyb': 'Kyoto-ben',
     'kyu': 'Kyuushuu-ben',
     'nab': 'Nagano-ben',
     'osb': 'Osaka-ben',
     'rkb': 'Ryuukyuu-ben',
     'std': 'Tokyo-ben (std)',
     'thb': 'Touhoku-ben',
     'tsb': 'Tosa-ben',
     'tsug': 'Tsugaru-ben',
   },
   language: {
     'eng': 'English',
     'afr': 'Afrikaans',
     'ain': 'Ainu',
     'alg': 'Algonquian languages',
     'amh': 'Amharic',
     'ara': 'Arabic',
     'arn': 'Mapudungun; Mapuche',
     'bnt': 'Bantu (Other',
     'bre': 'Breton',
     'bul': 'Bulgarian',
     'bur': 'Burmese',
     'chi': 'Chinese',
     'chn': 'Chinook jargon',
     'cze': 'Czech',
     'dan': 'Danish',
     'dut': 'Dutch; Flemish',
     'epo': 'Esperanto',
     'est': 'Estonian',
     'fil': 'Filipino; Pilipino',
     'fin': 'Finnish',
     'fre': 'French',
     'geo': 'Georgian',
     'ger': 'German',
     'glg': 'Galician',
     'grc': 'Greek, Ancient (to 1453)',
     'gre': 'Greek, Modern (1453-)',
     'haw': 'Hawaiian',
     'heb': 'Hebrew',
     'hin': 'Hindi',
     'hun': 'Hungarian',
     'ice': 'Icelandic',
     'ind': 'Indonesian',
     'ita': 'Italian',
     'khm': 'Central Khmer',
     'kor': 'Korean',
     'kur': 'Kurdish',
     'lat': 'Latin',
     'mal': 'Malayalam',
     'mao': 'Maori',
     'mas': 'Masai',
     'may': 'Malay',
     'mnc': 'Manchu',
     'mol': 'Moldavian',
     'mon': 'Mongolian',
     'nor': 'Norwegian',
     'per': 'Persian',
     'pol': 'Polish',
     'por': 'Portuguese',
     'rum': 'Romanian',
     'rus': 'Russian',
     'san': 'Sanskrit',
     'scr': 'Croatian',
     'slo': 'Slovak',
     'slv': 'Slovenian',
     'som': 'Somali',
     'spa': 'Spanish; Castilian',
     'swa': 'Swahili',
     'swe': 'Swedish',
     'tah': 'Tahitian',
     'tam': 'Tamil',
     'tha': 'Thai',
     'tib': 'Tibetan',
     'tur': 'Turkish',
     'urd': 'Urdu',
     'vie': 'Vietnamese',
     'yid': 'Yiddish',
   },
   glossaryInfo: {
     'equ': 'equivalent',
     'expl': 'explanatory',
     'fig': 'figuratively',
     'lit': 'literally',
   },
 };