name: Python Build

on:
  push:
    branches: [ "master" ]
    tags:
      - "release-*"
  pull_request:
    branches: [ "master" ]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { name: windows, os: windows-2019, msvc_arch: x64, cibw_arch: AMD64}
          - { name: windows, os: windows-2019, msvc_arch: x86, cibw_arch: x86}
          - { name: macos, os: macos-11, cibw_arch: auto}
          - { name: linux, os: ubuntu-20.04, cibw_arch: auto}

    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}
        if: matrix.name == 'windows'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
